# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DailyWork' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Alamofire'
  pod 'Alamofire-SwiftyJSON'
  pod 'HandyJSON'
  pod 'SnapKit'
  pod 'Kingfisher'
  pod 'MJRefresh'
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
 

end
